# Setup
title:        TechClub
baseurl:      ""
paginate:     1

# Assets
sass:
    sass_dir: _sass

# About/contact
author:
  name:       TechClub
  url:        http://techclub.nyc

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown